version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: todo
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: always
    container_name: db

  backend:
    depends_on:
      - db
    build: .
    command: bash -c "sleep 5 && flask db init && flask db migrate && flask db upgrade && flask run"    
    restart: always     
    ports:
      - "5050:5000"    
    container_name: backend

volumes:
  db-data:      